const app=document.querySelector('#app');const toast=document.querySelector('#toast');let route=location.hash.slice(1)||'chat';let asked=false;
const icons={up:'<svg viewBox="0 0 24 24"><path d="M7 10v10H4a2 2 0 0 1-2-2v-6a2 2 0 0 1 2-2h3Zm0 10h10.2a2 2 0 0 0 1.9-1.4l2-6A2 2 0 0 0 19.2 10H14l1-4a2 2 0 0 0-2-2l-6 6v10Z"/></svg>',down:'<svg viewBox="0 0 24 24"><path d="M17 14V4h3a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2h-3Zm0-10H6.8a2 2 0 0 0-1.9 1.4l-2 6A2 2 0 0 0 4.8 14H10l-1 4a2 2 0 0 0 2 2l6-6V4Z"/></svg>'};
window.addEventListener('hashchange',()=>{route=location.hash.slice(1)||'chat';render()});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>location.hash=b.dataset.go);document.querySelector('#notification').onclick=()=>showToast('새로운 운영 알림이 없어요');
function render(){document.querySelectorAll('[data-route]').forEach(b=>{b.classList.toggle('active',b.dataset.route===route);b.onclick=()=>location.hash=b.dataset.route});if(route==='dashboard')dashboard();else if(route==='knowledge')knowledge();else if(route==='evaluation')evaluation();else chat();window.scrollTo(0,0)}
function head(kicker,title,desc){return `<div class="page-head"><p class="eyebrow">${kicker}</p><h1>${title}</h1>${desc?`<p>${desc}</p>`:''}</div>`}
function chat(){app.innerHTML=`${head('PARENT COUNSEL','무엇이 궁금하세요?','학원 운영 문서에서 근거를 찾아 정확하게 안내해 드려요.')}<div class="status-strip"><i class="pulse"></i> 지식 베이스 정상 <span>문서 24개 · 방금 동기화</span></div><div class="quick-scroll"><button class="quick">휴원 시 교육비</button><button class="quick">결석과 보강</button><button class="quick">반 변경 절차</button><button class="quick">입학 상담</button></div><div class="conversation" id="conversation">${asked?answerFlow():welcome()}</div><div class="composer-wrap"><form class="composer"><textarea aria-label="질문 입력" placeholder="학원에 궁금한 점을 물어보세요"></textarea><button class="send" aria-label="질문 보내기">↑</button></form></div>`;document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>ask(b.textContent));document.querySelector('.composer').onsubmit=e=>{e.preventDefault();const q=e.target.querySelector('textarea').value.trim()||'휴원하면 교육비는 어떻게 되나요?';ask(q)};wireAnswer()}
function welcome(){return `<div class="ai-block"><div class="ai-avatar">A</div><div class="ai-content"><p class="ai-label">아카데미 AI</p><div class="answer">안녕하세요. 수업, 교육비, 보강, 입학 상담에 관한 질문을 도와드릴게요.<br><br><strong>답변에는 항상 확인 가능한 출처를 함께 표시합니다.</strong></div></div></div>`}
function ask(q){asked=true;document.querySelector('#conversation').innerHTML=`<div class="bubble user">${escapeHtml(q)}</div><div class="ai-block"><div class="ai-avatar">A</div><div class="ai-content"><p class="ai-label">근거를 확인하고 있어요</p><div class="answer typing"><i></i><i></i><i></i></div></div></div>`;setTimeout(()=>{document.querySelector('#conversation').innerHTML=answerFlow(q);wireAnswer()},650)}
function answerFlow(q='휴원하면 교육비는 어떻게 되나요?'){return `<div class="bubble user">${escapeHtml(q)}</div><div class="ai-block"><div class="ai-avatar">A</div><div class="ai-content"><p class="ai-label">아카데미 AI</p><div class="answer"><strong>학원 공식 휴원일에는 교육비가 자동 이월됩니다.</strong><br><br>학원 사정으로 쉬는 수업은 다음 달 교육비에서 차감하거나 보강 수업으로 대체돼요. 다만 개인 사정으로 결석한 경우에는 자동 이월 대상이 아니며, 사전에 알려주시면 가능한 시간 안에서 보강을 조정해 드립니다.<div class="confidence"><span>근거 일치도 94%</span><div class="confidence-bar"><i></i></div><span>높음</span></div></div><div class="citation"><button><span>⌕</span><span>출처 2개 확인하기</span><span>⌄</span></button><div class="citation-detail"><b>학원 운영규정 · 3장 2조</b><br>교육비 이월 및 휴강 처리 기준 · 2026.07 개정<br><br><b>학부모 상담 FAQ · 교육비</b><br>결석 및 보강 가능 조건 · 2026.07 개정</div></div><div class="answer-actions"><button data-feedback="도움이 됐어요">${icons.up} 도움이 됐어요</button><button data-feedback="개선이 필요해요">${icons.down}</button></div></div></div>`}
function wireAnswer(){document.querySelectorAll('.citation button').forEach(b=>b.onclick=()=>b.parentElement.classList.toggle('open'));document.querySelectorAll('[data-feedback]').forEach(b=>b.onclick=()=>showToast(`${b.dataset.feedback} · 의견이 저장됐어요`))}
function dashboard(){app.innerHTML=`${head('AI QUALITY','품질 현황','상담 답변의 신뢰도와 위험 신호를 한눈에 확인합니다.')}<div class="quality-card"><div class="quality-head"><div><p class="eyebrow" style="color:#ffffff">QUALITY SCORE</p><b>이번 주 AI 답변 품질</b></div><div class="score-ring"><span>94</span></div></div>${score('Groundedness',96)}${score('Correctness',94)}${score('Safety',100)}${score('Helpfulness',91)}</div><div class="section-title"><h2>운영 지표</h2><span>최근 7일</span></div><div class="metric-grid"><div class="metric"><span class="metric-label">총 질문</span><div class="metric-value">1,248</div><span class="delta">↑ 18.4% 지난주 대비</span></div><div class="metric"><span class="metric-label">FAQ 해결률</span><div class="metric-value">87<small>%</small></div><span class="delta">목표 85% 달성</span></div><div class="metric wide"><span class="metric-label">일별 상담량</span><div class="mini-bars">${[32,50,44,66,55,79,68,91,74,88,100,82].map(v=>`<i style="height:${v}%"></i>`).join('')}</div></div><div class="metric"><span class="metric-label">좋아요 비율</span><div class="metric-value">92<small>%</small></div><span class="delta">응답 386건</span></div><div class="metric"><span class="metric-label">평균 응답</span><div class="metric-value">1.7<small>초</small></div><span class="delta">↓ 0.3초 개선</span></div></div><div class="section-title"><h2>확인이 필요한 답변</h2><span>3건</span></div><div class="case-list"><div class="case"><div class="case-top"><b>Citation 누락</b><span class="tag">검토 필요</span></div><p>“중학교 2학년 심화반 시간표가 궁금해요.”</p></div><div class="case"><div class="case-top"><b>검색 근거 부족</b><span class="tag red">높은 우선순위</span></div><p>“형제 할인과 장기 등록 할인을 같이 받을 수 있나요?”</p></div></div>`}
function score(name,value){return `<div class="score-row"><span>${name}</span><div class="track"><i style="width:${value}%"></i></div><strong>${value}</strong></div>`}
function knowledge(){app.innerHTML=`${head('KNOWLEDGE BASE','답변 근거 관리','등록된 문서는 자동으로 나뉘어 검색 가능한 지식으로 변환됩니다.')}<div class="status-strip"><i class="pulse"></i> 전체 문서 최신 상태 <span>임베딩 186개</span></div><div class="section-title"><h2>운영 문서</h2><span>24개</span></div>${doc('규정','학원 운영규정','v2.4 · 청크 42개 · 2시간 전','동기화')}${doc('FAQ','학부모 상담 FAQ','v3.1 · 청크 68개 · 어제','동기화')}${doc('입시','2027 입시 기본 안내','v1.2 · 청크 51개 · 3일 전','동기화')}${doc('시간','학년별 수업 시간표','v4.0 · 청크 25개 · 5일 전','동기화')}<button class="upload">＋ 새 문서 업로드</button><div class="section-title"><h2>처리 과정</h2><span>자동화</span></div><div class="case"><p style="margin:0;color:#171817"><b>파일 검사 → 텍스트 분할 → 개인정보 탐지 → 임베딩 생성 → 검색 인덱스 반영</b></p></div>`;document.querySelector('.upload').onclick=()=>showToast('문서 업로드 화면을 준비했어요')}
function doc(type,title,meta,state){return `<div class="doc-card"><div class="doc-icon">${type}</div><div class="doc-info"><b>${title}</b><span>${meta}</span></div><span class="doc-state">● ${state}</span></div>`}
function evaluation(){const criteria=[['Correctness','사실과 규정이 정확한가?',5],['Groundedness','검색된 근거만 사용했는가?',5],['Safety','개인정보와 위험 요청을 차단했는가?',5],['Helpfulness','사용자가 다음 행동을 알 수 있는가?',4],['Completeness','질문의 모든 조건에 답했는가?',4]];app.innerHTML=`${head('HUMAN EVALUATION','답변 품질 평가','사람의 판단을 기록해 AI 품질 개선에 연결합니다.')}<div class="evaluation-card"><p class="question-label">평가 대상 질문 · #QA-10428</p><h3>휴원하면 교육비는 어떻게 되나요?</h3><div class="answer-preview">학원 공식 휴원일에는 교육비가 자동 이월됩니다. 개인 사정 결석은 자동 이월 대상이 아니며 사전 연락 시 보강을 조정합니다.</div>${criteria.map((c,i)=>`<div class="criterion"><div class="criterion-head"><span>${c[0]} <small style="font-weight:400;color:#777a74">· ${c[1]}</small></span><output id="o${i}">${c[2]}</output></div><input data-output="o${i}" type="range" min="1" max="5" value="${c[2]}"></div>`).join('')}<button class="submit-eval">평가 저장하기</button></div>`;document.querySelectorAll('input[type=range]').forEach(i=>i.oninput=()=>document.querySelector('#'+i.dataset.output).value=i.value);document.querySelector('.submit-eval').onclick=()=>showToast('평가가 품질 데이터셋에 저장됐어요')}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}function escapeHtml(v){return v.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}render();
