create table if not exists public.chart_publications (
  chart_date date primary key,
  generated_at timestamptz not null,
  published_at timestamptz not null default now(),
  status text not null default 'published',
  public_limit integer not null default 25,
  candidate_count integer not null default 50,
  chart jsonb not null
);

create index if not exists chart_publications_status_published_at_idx
  on public.chart_publications (status, published_at desc);

create table if not exists public.chart_admin_audits (
  id bigint generated by default as identity primary key,
  published_at timestamptz not null default now(),
  chart_date date not null,
  previous_generated_at timestamptz,
  new_generated_at timestamptz not null,
  public_limit integer not null default 25,
  candidate_count integer not null default 50,
  changed_review_scores jsonb not null default '[]'::jsonb,
  chart jsonb not null
);

alter table public.chart_publications enable row level security;
alter table public.chart_admin_audits enable row level security;

drop policy if exists "public can read published charts" on public.chart_publications;
create policy "public can read published charts"
  on public.chart_publications
  for select
  using (status = 'published');
